AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-bff-oauth2

  Sample SAM Template for serverless-bff-oauth2
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CheckSessionFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/api-proxy/
      Handler: session.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        GetSessionInfo:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /session
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - session.ts
  OauthRedirectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/api-proxy
      Handler: auth.lambdaHandler
      Runtime: nodejs20.x
      Events:
        CreateSession:
          Type: Api
          Properties:
            Path: /auth
            Method: get
    Metadata:
        BuildMethod: esbuild
        BuildProperties:
          Minify: true
          Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - auth.ts
  OauthLoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/api-proxy
      Handler: login.lambdaHandler
      Runtime: nodejs20.x
      Events:
        Login:
          Type: Api
          Properties:
            Path: /login
            Method: get
    Metadata:
        BuildMethod: esbuild
        BuildProperties:
          Minify: true
          Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - login.ts
Outputs:
  CheckSessionFunction:
    Value: !GetAtt CheckSessionFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
